server:
  port: 8082

spring:
  application:
    name: order-service
  sql:
    init:
      mode: always

  rabbitmq:
    host: localhost
    port: 5672

  r2dbc:
    url: r2dbc:postgresql://localhost:5437/tickets_db
    username: myuser
    password: mypassword

  cloud:
    function:
      definition: paymentEvents
    stream:
      bindings:
        paymentEvents-in-0:
          destination: payment.completed.events
          group: order-service-group
          content-type: application/json
          consumer:
            max-attempts: 5
      rabbit:
        bindings:
          paymentEvents-in-0:
            consumer:
              auto-bind-dlq: true
              requeue-rejected: false

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: "${JWT_KEY}"

resilience4j:
  circuitbreaker:
    instances:
      eventServiceBreaker:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2