server:
  port: 8081

spring:
  application:
    name: event-service

  datasource:
    url: jdbc:postgresql://localhost:5437/tickets_db
    username: myuser
    password: mypassword


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:5000
